#!/bin/bash
function getdir(){
	for element in `ls $1`; do  
		dir_or_file="$1/$element"
		if [ -d "$dir_or_file" ];then
			getdir "$dir_or_file"
		else
			echo "$dir_or_file"
		fi
	done
}
if [ -z "$1" ]; then
	Dir2Tree=$PWD;
else
	Dir2Tree=$1;
fi
getdir $Dir2Tree
