#!/bin/bash
### FuhaoBash_FileMod bash modules
###Descriptions:
#	File/folder related subfunctions



#Author:
#  Fu-Hao Lu
#  Post-Doctoral Scientist in Micheal Bevan laboratory
#  Cell and Developmental Department, John Innes Centre
#  Norwich NR4 7UH, United Kingdom
#  E-mail: Fu-Hao.Lu@jic.ac.uk



### Return full path of a file or folder
abs2rel () {
	perl -MFile::Spec -e 'print(File::Spec->abs2rel($ARGV[1], $ARGV[0]), "\n")' "$@";
}
function fullpath() {
    # generate absolute path from relative path
    # $1     : relative filename
    # return : absolute path
    if [ -d "$1" ]; then
        # dir
        (cd "$1"; pwd)
    elif [ -f "$1" ]; then
        # file
        if [[ $1 == */* ]]; then
            echo "$(cd "${1%/*}"; pwd)/${1##*/}"
        else
            echo "$(pwd)/$1"
        fi
    fi
}
abspath () { case "$1" in /*)printf "%s\n" "$1";; *)printf "%s\n" "$PWD/$1";; esac; }
#for zsh only
#realpath() { for f in "$@"; do echo ${f}(:A); done }
echo `cd "$1" 2>/dev/null&&pwd||(cd "$(dirname "$1")";pwd|sed "s|/*\$|/${1##*/}|")`
fp () {
  case "$1" in
    /*) printf '%s\n' "$1";;
    *) printf '%s\n' "$PWD/$1";;
  esac
}
rel2abs () {
	
	for RAfile in $@; do
		RAfull=$(echo $(cd $(dirname "$RAfile"); pwd)/$(basename "$RAfile"))
		echo "$RAfull"
	done

}
#rel2abs () { perl -MFile::Spec -e \'print(File::Spec->rel2abs($ARGV[0]), "\n")\' "$@"; }


File2Fullpath () {
	local FFinput=$1
	local FFsubinfo="SUF(File2Fullpath)"
	
#	echo "#Test1: $FFinput #" >&2
	if [[ "$FFinput" =~ .*\/.* ]]; then
		if [[ "$FFinput" =~ ^\/ ]]; then
#			echo "#Test2: $FFinput #" >&2
			echo $FFinput
		else
#			echo "#Test3: $FFinput #" >&2
			echo $(cd $(dirname "$FFinput"); pwd)/$(basename "$FFinput")
		fi
	elif [[ "$FFinput" =~ ^[-0-9a-zA-Z\._]+$ ]]; then
#		echo "#Test4: $FFinput #" >&2
		echo $(pwd)/$(basename "$FFinput")
	else
#		echo "#Test5: $FFinput #" >&2
		echo ''
	fi
#	echo "#Test6: $FFinput #" >&2
}
