#!/bin/bash
### bash modules
###Descriptions:
#	Fastq related subfunctions



#Author:
#  Fu-Hao Lu
#  Post-Doctoral Scientist in Micheal Bevan laboratory
#  Cell and Developmental Department, John Innes Centre
#  Norwich NR4 7UH, United Kingdom
#  E-mail: Fu-Hao.Lu@jic.ac.uk




### run fastqc to 
### FastqPairnessCheck(fq, options)
### Program: fastqc
### Global: $numthreads
### Options: " --nogroup -o ./nogroup ", " -o ./group "
### Note: ./nogroup or ./group must exists
FastQCheck () {
	FQCfastq=$1
	FQCoptions=$2
	
	if [ -z "$FQCoptions" ]; then
		FQCoptions=" -o $PWD/nogroup -t 1  --noextract --nogroup"
	fi
	fastqc $FQCfastq -f fastq $FQCoptions
	if [ $? -ne 0 ]; then
		return 100;
	fi
	
	return 0
}


### check read Pairness in fastq R1 and R2
### FastqPairnessCheck(R1.fq, R2.fq, outpfx)
### Program: fastq_checkid.pl
### Global:
FastqPairnessCheck () {
	local FPCfqR1=$1
	local FPCfqR2=$2
	local FPCoutpfx=$3
	
	local FPCsubinfo="FuhaoBash_FastqMod(FastqPairnessCheck)"
	
	fastq_checkid.pl $FPCfqR1 $FPCfqR2 '\@(\S+)\s*\S*'
	if [ $? -eq 0 ]; then
		echo "${FPCsubinfo}Info: $FPCoutpfx paired"
		touch ${FPCoutpfx}_paired
	else
		echo "${FPCsubinfo}Warnings: $FPCoutpfx un-paired" >&2
		touch ${FPCoutpfx}_unpaired
	fi
	return 0
}



### run Trim_Galore
### RunTrimGalore (fq1gz, fq2gz, options, $numthreads, fqout1, fqout2)
### options="--paired --gzip --output_dir ./ --quality 20 --phred33 --nextera --length 70 --trim1"
### CMD: fastqc, trim_galore
### Global:
RunTrimGalore () {
	local RTGfq1=$1
	local RTGfq2=$2
	local RTGoption=$3
	local RTGnumthreads=$4
	local RTGfqout1=$5
	local RTGfqout2=$6
	local RTGsubinfo="FuhaoBash_FastqMod(RunTrimGalore)"

	RTGfq1out_base=${RTGfq1##*/}
	RTGfq1out=$(echo "$RTGfq1out_base"| perl -lne 's/\.gz$//i;s/(\.fastq)|(\.fq)$//i;print $_, "_val_1.fq.gz";')
	RTGfq2out_base=${RTGfq2##*/}
	RTGfq2out=$(echo "$RTGfq2out_base"| perl -lne 's/\.gz$//i;s/(\.fastq)|(\.fq)$//i;print $_, "_val_2.fq.gz";')

	echo "${RTGsubinfo}Error: Input Fq R1: $RTGfq1"
	echo "${RTGsubinfo}Error: Input Fq R2: $RTGfq2"
	echo "${RTGsubinfo}Error: Temp Fq R1: $RTGfq1out"
	echo "${RTGsubinfo}Error: Temp Fq R2: $RTGfq2out"
	echo "${RTGsubinfo}Error: Output Fq R1: $RTGfqout1"
	echo "${RTGsubinfo}Error: Output Fq R2: $RTGfqout2"

	local RTGoutdir1=$(dirname $RTGfqout1)
	if [ ! -d $RTGoutdir1 ]; then
		mkdir -p $RTGoutdir1
	fi
	local RTGoutdir2=$(dirname $RTGfqout2)
	if [ ! -d $RTGoutdir2 ]; then
		mkdir -p $RTGoutdir2;
	fi
	
	trim_galore $RTGoption $RTGfq1 $RTGfq2
	if [ $? -ne 0 ]; then
		echo "${RTGsubinfo}Error: trim_galore running error" >&2
		return 100
	fi
	
	if [ -s $RTGfq1out ]; then
		mv $RTGfq1out $RTGfqout1
	fi
	if [ -s $RTGfqout1 ]; then
#		if [ ! -d $RTGoutdir1/group ]; then
#			mkdir -p $RTGoutdir1/group
#		fi
#		fastqc $RTGfqout1 -o $RTGoutdir1/group -f fastq -t $RTGnumthreads --noextract
		if [ ! -d $RTGoutdir1/nogroup ]; then
			mkdir -p $RTGoutdir1/nogroup
		fi
		if FastQCheck $RTGfqout1 " -o $RTGoutdir1/nogroup -t $RTGnumthreads  --noextract --nogroup"; then
			echo "Info: fastqc succeeded: $RTGfqout1"
		else
			echo "Error: fastqc failed: $RTGfqout1" >&2
			return 100
		fi
	else
		return 100
	fi
	if [ -s $RTGfq2out ]; then
		mv $RTGfq2out $RTGfqout2
	fi
	if [ -s $RTGfqout2 ]; then
#		if [ ! -d $RTGoutdir2/group ]; then
#			mkdir -p $RTGoutdir2/group
#		fi
#		fastqc $RTGfqout2 -o $RTGoutdir2/group -f fastq -t $RTGnumthreads --noextract
		if [ ! -d $RTGoutdir2/nogroup ]; then
			mkdir -p $RTGoutdir2/nogroup
		fi
		if FastQCheck $RTGfqout2 " -o $RTGoutdir2/nogroup -t $RTGnumthreads  --noextract --nogroup"; then
			echo "Info: fastqc succeeded: $RTGfqout2"
		else
			echo "Error: fastqc failed: $RTGfqout2" >&2
			return 100
		fi
	else
		return 100
	fi

	return 0
}



### trimmomatic
### RunTrimmomatic(R1.fq[.gz], R2.fq[.gz], file_adaptors, path_trimmomatic, outfq1_paired, outfq2_paired, outprefix, outlog, Min_qual, Min_length)
### Global: numthreads
### Program: fastqc
### Output: $Trimmomatic_out_fq1 $Trimmomatic_out_fq2
RunTrimmomatic () {
	local RMr1=$1
	local RMr2=$2
	local RMpath_trimmomatic=$3
	local RMfile_adaptor=$4
	local RMoutfq1_paired=$5
	local RMoutfq2_paired=$6
	local RMoutpfx=$7
	local RMmin_qual=$8
	local RMmin_len=$9
	local RMnumthreads=${10}
	
	local RMsubinfo="FuhaoBash_FastqMod(RunTrimmomatic)"
	local RMoutfq1_unpaired="$RMoutpfx.R1.unpaired.fq.gz"
	local RMoutfq2_unpaired="$RMoutpfx.R2.unpaired.fq.gz"
	local RMoutlog="$RMoutpfx.trimmomatic.log"
	if [ -z "$RMmin_qual" ]; then
		RMmin_qual=15
	fi
	if [ -z "$RMmin_len" ]; then
		RMmin_len=70
	fi
	if [ -z "$RMnumthreads" ]; then
		RMnumthreads=1
	fi
	local RMpathdir1=$(dirname $RMoutfq1_paired)
	if [ ! -d $RMpathdir1 ]; then
		mkdir -p $RMpathdir1
	fi
	local RMpathdir2=$(dirname $RMoutfq2_paired)
	if [ ! -d $RMpathdir2 ]; then
		mkdir -p $RMpathdir2
	fi
	local RMpathdir3=$(dirname $RMoutfq1_unpaired)
	if [ ! -d $RMpathdir3 ]; then
		mkdir -p $RMpathdir3
	fi
	local RMpathdir4=$(dirname $RMoutfq2_unpaired)
	if [ ! -d $RMpathdir4 ]; then
		mkdir -p $RMpathdir4
	fi
	local RMpathdir5=$(dirname $RMoutlog)
	if [ ! -d $RMpathdir5 ]; then
		mkdir -p $RMpathdir5
	fi
#Parameters
	
	echo "${RMsubinfo}Info: fastq R1        : $RMr1"
	echo "${RMsubinfo}Info: fastq R2        : $RMr2"
	echo "${RMsubinfo}Info: Adaptors        : $RMfile_adaptor"
	echo "${RMsubinfo}Info: Trimmomatic path: $RMpath_trimmomatic"
	echo "${RMsubinfo}Info: Min Qual        : $RMmin_qual"
	echo "${RMsubinfo}Info: Min Length      : $RMmin_len"
	
	if [ -s $RMpath_trimmomatic ]; then
		java -jar $RMpath_trimmomatic PE -threads $RMnumthreads -phred33 \
		-trimlog $RMoutlog \
		$RMr1 \
		$RMr2 \
		$RMoutfq1_paired $RMoutfq1_unpaired \
		$RMoutfq2_paired $RMoutfq2_unpaired \
		ILLUMINACLIP:"$RMfile_adaptor":2:30:10 LEADING:$RMmin_qual TRAILING:$RMmin_qual SLIDINGWINDOW:4:$RMmin_qual MINLEN:$RMmin_len
	else
		java org.usadellab.trimmomatic.TrimmomaticPE -threads $RMnumthreads -phred33 \
		-trimlog $RMoutlog \
		$RMr1 \
		$RMr2 \
		$RMoutfq1_paired $RMoutfq1_unpaired \
		$RMoutfq2_paired $RMoutfq2_unpaired \
		ILLUMINACLIP:"$RMfile_adaptor":2:30:10 LEADING:$RMmin_qual TRAILING:$RMmin_qual SLIDINGWINDOW:4:$RMmin_qual MINLEN:$RMmin_len
	fi

	if [ -s $RMoutfq1_paired ]; then
		if [ ! -d $RMpathdir1/nogroup ]; then
			mkdir -p $RMpathdir1/nogroup
		fi
		if FastQCheck $RMoutfq1_paired " -o $RMpathdir1/nogroup -t $RMnumthreads  --noextract --nogroup"; then
			echo "Info: fastqc succeeded: $RMoutfq1_paired"
		else
			echo "Error: fastqc failed: $RMoutfq1_paired" >&2
			return 100
		fi
	fi
	if [ -s $RMoutfq2_paired ]; then
		if [ ! -d $RMpathdir2/nogroup ]; then
			mkdir -p $RMpathdir2/nogroup
		fi
		if FastQCheck $RMoutfq2_paired " -o $RMpathdir2/nogroup -t $RMnumthreads  --noextract --nogroup"; then
			echo "Info: fastqc succeeded: $RMoutfq2_paired"
		else
			echo "Error: fastqc failed: $RMoutfq2_paired" >&2
			return 100
		fi
	fi

	return 0
}
### run trimmomatic using classpath
### RunTrimmomatic2 in1.fq.gz in2.fq.gz out1.fq.gz out2.fq.gz out.prefix in.adaptor min.qual min.len num_threads
RunTrimmomatic2 () {
	local RMr1=$1
	local RMr2=$2
	local RMoutfq1_paired=$3
	local RMoutfq2_paired=$4
	local RMoutpfx=$5
	local RMfile_adaptor=$6
	local RMmin_qual=$7
	local RMmin_len=$8
	local RMnumthreads=$9
	
	local RMsubinfo="FuhaoBash_FastqMod(RunTrimmomatic2)"
	local RMoutfq1_unpaired="$RMoutpfx.R1.unpaired.fq.gz"
	local RMoutfq2_unpaired="$RMoutpfx.R2.unpaired.fq.gz"
	local RMoutlog="$RMoutpfx.trimmomatic.log"
	if [ -z "$RMmin_qual" ]; then
		RMmin_qual=15
	fi
	if [ -z "$RMmin_len" ]; then
		RMmin_len=70
	fi
	if [ -z "$RMnumthreads" ]; then
		RMnumthreads=1
	fi
	local RMpathdir1=$(dirname $RMoutfq1_paired)
	if [ ! -d $RMpathdir1 ]; then
		mkdir -p $RMpathdir1
	fi
	local RMpathdir2=$(dirname $RMoutfq2_paired)
	if [ ! -d $RMpathdir2 ]; then
		mkdir -p $RMpathdir2
	fi
	local RMpathdir3=$(dirname $RMoutfq1_unpaired)
	if [ ! -d $RMpathdir3 ]; then
		mkdir -p $RMpathdir3
	fi
	local RMpathdir4=$(dirname $RMoutfq2_unpaired)
	if [ ! -d $RMpathdir4 ]; then
		mkdir -p $RMpathdir4
	fi
	local RMpathdir5=$(dirname $RMoutlog)
	if [ ! -d $RMpathdir5 ]; then
		mkdir -p $RMpathdir5
	fi
#Parameters
	
	echo "${RMsubinfo}Info: fastq R1        : $RMr1"
	echo "${RMsubinfo}Info: fastq R2        : $RMr2"
	echo "${RMsubinfo}Info: Adaptors        : $RMfile_adaptor"
	echo "${RMsubinfo}Info: Min Qual        : $RMmin_qual"
	echo "${RMsubinfo}Info: Min Length      : $RMmin_len"
	
	java org.usadellab.trimmomatic.TrimmomaticPE -threads $RMnumthreads -phred33 \
		-trimlog $RMoutlog \
		$RMr1 \
		$RMr2 \
		$RMoutfq1_paired $RMoutfq1_unpaired \
		$RMoutfq2_paired $RMoutfq2_unpaired \
		ILLUMINACLIP:"$RMfile_adaptor":2:30:10 LEADING:$RMmin_qual TRAILING:$RMmin_qual SLIDINGWINDOW:4:$RMmin_qual MINLEN:$RMmin_len

	if [ -s $RMoutfq1_paired ]; then
		if [ ! -d $RMpathdir1/nogroup ]; then
			mkdir -p $RMpathdir1/nogroup
		fi
		if FastQCheck $RMoutfq1_paired " -o $RMpathdir1/nogroup -t $RMnumthreads  --noextract --nogroup"; then
			echo "Info: fastqc succeeded: $RMoutfq1_paired"
		else
			echo "Error: fastqc failed: $RMoutfq1_paired" >&2
			return 100
		fi
	fi
	if [ -s $RMoutfq2_paired ]; then
		if [ ! -d $RMpathdir2/nogroup ]; then
			mkdir -p $RMpathdir2/nogroup
		fi
		if FastQCheck $RMoutfq2_paired " -o $RMpathdir2/nogroup -t $RMnumthreads  --noextract --nogroup"; then
			echo "Info: fastqc succeeded: $RMoutfq2_paired"
		else
			echo "Error: fastqc failed: $RMoutfq2_paired" >&2
			return 100
		fi
	fi

	return 0
}



### run trimmomatic using classpath
RunFastp () {
	local RFr1=$1
	local RFr2=$2
	local RFoutfq1_paired=$3
	local RFoutfq2_paired=$4
	local RFoutpfx=$5
	local RFmin_qual=$6
	local RFmin_len=$7
	local RFnumthreads=$8
	local RFoptions=$9
	
	local RFsubinfo="FuhaoBash_FastqMod(RunFastp)"
	local RFoutfq1_unpaired="$RFoutpfx.R1.unpaired.fq.gz"
	local RFoutfq2_unpaired="$RFoutpfx.R2.unpaired.fq.gz"
	if [ -z "$RFmin_qual" ]; then
		RFmin_qual=15
	fi
	if [ -z "$RFmin_len" ]; then
		RFmin_len=70
	fi
	if [ -z "$RFnumthreads" ]; then
		RFnumthreads=1
	fi
	if [ -z "$RFoptions" ]; then
		RFoptions=" --compression 9 --cut_tail --cut_window_size 4"
	fi
	local RFpathdir1=$(dirname $RFoutfq1_paired)
	if [ ! -d $RFpathdir1 ]; then
		mkdir -p $RFpathdir1
	fi
	local RFpathdir2=$(dirname $RFoutfq2_paired)
	if [ ! -d $RFpathdir2 ]; then
		mkdir -p $RFpathdir2
	fi
	local RFpathdir3=$(dirname $RFoutfq1_unpaired)
	if [ ! -d $RFpathdir3 ]; then
		mkdir -p $RFpathdir3
	fi
	local RFpathdir4=$(dirname $RFoutfq2_unpaired)
	if [ ! -d $RFpathdir4 ]; then
		mkdir -p $RFpathdir4
	fi
#Parameters
	
	echo "${RFsubinfo}Info: fastq R1        : $RFr1"
	echo "${RFsubinfo}Info: fastq R2        : $RFr2"
	echo "${RFsubinfo}Info: Min Qual        : $RFmin_qual"
	echo "${RFsubinfo}Info: Min Length      : $RFmin_len"
	echo "${RFsubinfo}Info: threads         : $RFnumthreads"
	echo "${RFsubinfo}Info: options         : $RFoptions"

	fastp -i $RFr1 -o $RFoutfq1_paired -I $RFr2 -O $RFoutfq2_paired --unpaired1 $RFoutfq1_unpaired --unpaired2 $RFoutfq2_unpaired \
	--thread $RFnumthreads --length_required $RFmin_len --cut_mean_quality $RFmin_qual --overrepresentation_analysis --html $RFoptions
	if [ $? -ne 0 ]; then
		echo "Error: fastp running error" >&2
		echo "CMD used: fastp -i $RFr1 -o $RFoutfq1_paired -I $RFr2 -O $RFoutfq2_paired --unpaired1 $RFoutfq1_unpaired --unpaired2 $RFoutfq2_unpaired --thread $RFnumthreads --length_required $RFmin_len --cut_mean_quality $RFmin_qual --overrepresentation_analysis --html $RFoptions" >&2
		exit 100
	fi

	if [ -s $RFoutfq1_paired ]; then
		if [ ! -d $RFpathdir1/nogroup ]; then
			mkdir -p $RFpathdir1/nogroup
		fi
		if FastQCheck $RFoutfq1_paired " -o $RFpathdir1/nogroup -t $RFnumthreads  --noextract --nogroup"; then
			echo "Info: fastqc succeeded: $RFoutfq1_paired"
		else
			echo "Error: fastqc failed: $RFoutfq1_paired" >&2
			return 100
		fi
	fi
	if [ -s $RFoutfq2_paired ]; then
		if [ ! -d $RFpathdir2/nogroup ]; then
			mkdir -p $RFpathdir2/nogroup
		fi
		if FastQCheck $RFoutfq2_paired " -o $RFpathdir2/nogroup -t $RFnumthreads  --noextract --nogroup"; then
			echo "Info: fastqc succeeded: $RFoutfq2_paired"
		else
			echo "Error: fastqc failed: $RFoutfq2_paired" >&2
			return 100
		fi
	fi

	return 0
}
