#!/bin/bash


declare -a FuhaoArr=("FuhaoLab" "FuhaoBin" "FuhaoPerl5Lib" "ATACseqMappingPipeline")

for IndLib in ${FuhaoArr[@]}; do
	cd /home/hpcsoft/TestSoft
	echo -e "\n\n\n###$IndLib"
	if [ ! -d /home/hpcsoft/TestSoft/$IndLib ]; then
		cd /home/hpcsoft/TestSoft
		git clone https://github.com/lufuhao/$IndLib.git
	else
		cd /home/hpcsoft/TestSoft/$IndLib
		git pull
	fi
done

declare -a FuhaoArr=("FuhaoPerl5Lib")
for IndLib in ${FuhaoArr[@]}; do
        cd /home/hpcsoft/TestSoft
	echo -e "\n\n\n###$IndLib"
        if [ ! -d /home/hpcsoft/TestSoft/$IndLib ]; then
                mkdir -p /home/hpcsoft/TestSoft/$IndLib
		cd /home/hpcsoft/TestSoft/$IndLib
	fi
	if [ ! -d /home/hpcsoft/TestSoft/$IndLib/$IndLib ]; then
		cd /home/hpcsoft/TestSoft/$IndLib
			git clone https://github.com/lufuhao/$IndLib.git
		else
			cd /home/hpcsoft/TestSoft/$IndLib/$IndLib
			git pull
			fi
done

