#!/bin/bash

debug_mode=0
is_empty_dir(){ 
    return `ls -A $1|wc -w`
}
DeleteEmptyDir() {
	local -a dirArr=("$@")
	
	for indDir in ${dirArr[@]}; do
		if is_empty_dir $indDir; then
			rmdir $indDir
		fi
	done
}
listFolders(){
	local dirPath=$1

	for file in `ls -A $dirPath`; do
		if [ -d $dirPath/$file ]; then
			echo "    $file"
		fi
	done
}


while read -p "Please select 1. ProdSoft 2. TestSoft 0 Exit, [1/2/0]: " progType; do
	progPath=${PROGPATH}
	if [ $progType -eq 0 ]; then
		exit 0
	elif [ $progType -eq 1 ]; then
		progPath=/home/hpcsoft/ProdSoft
	elif [ $progType -eq 2 ]; then
		progPath=/home/hpcsoft/TestSoft
	fi
	echo "### Program Path selected: $progType"
	
	echo -e "\n"
	read -p "Please write Program Name: " progName

	if [ -z "$progName" ]; then
		continue
	elif [ -d $progPath/$progName ]; then
		echo "### Program Name valid: $progName"
	elif [ -d $progPath/libraries/$progName ]; then
                echo "### Libraries Program Name valid: $progName"
		progPath="$progPath/libraries"
	else
		echo "Error: Program Name invalid: $progName; Please try again" >&2
		if [ $debug_mode -eq 1 ]; then
			echo "    ### progType: $progType; progPath: $progPath; progName: $progName" >&2
		fi
		exit 100
	fi

	echo -e "\n"
	echo "Info: availble versions:"
        listFolders $progPath/$progName
	read -p "Please write Program Version: " progVers
	if [ -d $progPath/$progName/$progVers ]; then
                echo "### Program Version valid: $progVers"
		if [ -z "$progVers" ]; then
			rm -rf $progPath/$progName
			if [ -e $progPath/bin/$progName ]; then
				rm $progPath/bin/$progName
			else
				echo "Warnings: NOT found in bin: $progName" >&2
			fi
			if [ -e $progPath/bin/modules/$progName ]; then
				rm $progPath/bin/modules/$progName
			else
				echo "Warnings: NOT found in modules: $progName" >&2
			fi
		else
			rm -rf $progPath/$progName/$progVers
			if [ -e $progPath/bin/$progName-$progVers ]; then
                                rm $progPath/bin/$progName-$progVers
			else
				echo "Warnings: NOT found in bin: $progName-$progVers" >&2
                        fi
                        if [ -e $progPath/bin/modules/$progName/$progVers ]; then
                                rm $progPath/bin/modules/$progName/$progVers
				DeleteEmptyDir $progPath/bin/modules/$progName
			else
				echo "Warnings: NOT found in modules: $progName/$progVers" >&2
                        fi
		fi
        else
                echo "### Program Version invalid: $progVers; Please try again" >&2
                exit 100
        fi
	
	DeleteEmptyDir $progPath/$progName

done
